---
- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
  - php5
  - php5-common
  - php5-mysqlnd
  - php5-mcrypt
  - php5-curl
  - php5-cli
  - php5-gd
  - php-pear

- name: Enable php5-mcrypt
  command: php5enmod mcrypt
  notify:
    - reload apache
